all:
  children:
    webservers:
      hosts:
        ec2-server-1:
          ansible_host: 15.207.112.73
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./ansiblekey.pem
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ec2-server-2:
          ansible_host: 13.203.216.177
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./ansiblekey.pem
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ec2-server-3:
          ansible_host: 13.203.222.160
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./ansiblekey.pem
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ec2-server-4:
          ansible_host: 15.206.189.114
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ./ansiblekey.pem
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      vars:
        ansible_python_interpreter: /usr/bin/python3
